### ISSUE TITLE
Did you test for astc textures with alpha channel?

### ISSUE THREAD

**Issue by rockingdice** [susan31213-a/astc-in-cocos2d-3.17#1]
I read your post from https://hackerslab.aktsk.jp/2022/12/24/143955, it's awesome.

I'm using 3.17 as well, and want to try the astc textures.

I've followed your steps, but cannot use textures with an alpha channel, it's weird for the blending, and I don't get a clue where the problem is. I did upgrade all OpenGL es 2.0 codes to 3.0.

Also, I noticed that you don't change all OpenGL es 2.0 codes to migrate to 3.0, it's alright to only change the OpenGL context to 3.0, and use the astc textures?

**Comment by rockingdice** [comment]
It turns out that I should not use the multisample feature. It works great! Thank you. 
Do you try the android platform?

**Comment by susan31213-a** [comment]
@rockingdice 
Hello!
Sorry for the late reply.
I'm really surprised that someone read the blog and come to this repository! Thank you! 🙇 
I only try it on iOS. Did you try it on Android? If there is any problem, maybe I can help.

**Comment by rockingdice** [comment]
It's a big upgrade for cocos2d-x to support astc textures, so it's very useful and your work is valuable.
I did try it on Android, it's working and I don't have any other issues.
